pipeline:
  stages:
    - name: stage_bd4b
      id: stage_bd4b
      steps:
        - name: run1
          run:
            script: |-
              echo "running pipeline from another repo and dev branch"
              exit 0
          id: run1
          timeout: ${{inputs.timeout}}
  inputs:
    timeout:
      type: string
      label: timeout
