pipeline:
  name: pipe-parent-expression1
  identifier: pipeparentexpression1
  tags: {}
  projectIdentifier: edgartest
  orgIdentifier: default
  stages:
    - stage:
        name: print-trigger
        identifier: printtrigger
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "trigger expression"
                          echo <+trigger>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: run-child
        identifier: runchild
        description: ""
        type: Pipeline
        spec:
          org: default
          project: edgartest
          pipeline: childpipe1
          gitBranch: devtest
          inputSetReferences:
            - inputset06March
